name: PR Labeler

on:
  workflow_call:
    inputs:
      configuration-path:
        description: 'Path to the labeler configuration file'
        required: false
        type: string
        default: '.github/labeler.yml'

permissions: {}

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ${{ inputs.configuration-path }}
